version: '3'
services:
  database:
    image: postgres:12-bullseye
    container_name: postgres-container
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dump:/docker-entrypoint-initdb.d/
    networks:
      - api_network

volumes:
  postgres_data:

networks:
  api_network:
    driver: bridge
